### ISSUE TITLE
SSH shell session exits after the first command is executed.

### ISSUE THREAD

**Issue by lomaxfrog** [esnet/netshell#28]
title says it all.

**Comment by sowmyab** [comment]
Although, this fixed the issue for some of the netshell commands, when I execute python scripts in the ssh shell, netshell executes the script and immediately terminates the ssh session.(Bruce is also seeing the same issue. In fact, Bruce was the one who mentioned this first.)

**Comment by bmah888** [comment]
I think I know what's going on.  Testing a possible fix.
