### ISSUE TITLE
netshell-python doesn't find Python libraries

### ISSUE THREAD

**Issue by bmah888** [esnet/netshell#3]
Stumbled upon by @lomaxfrog:

Jython ships with a number of Python libraries, such as the json library.  For some reason, the jython-standalone bundle (Jython 2.7b4) can't find them, even though they're in the JAR in the ```Lib/``` directory.  We should be able to solve this by adding ```__pyclasspath__/Lib``` to ```sys.path``` like this:
```
sys.path = sys.path + ['__pyclasspath__/Lib']
```
But this doesn't work.

**Comment by lomaxfrog** [comment]
With the lastest changes, I believe this issue has became a non issue. Bruce would you agree ?
