### ISSUE TITLE
Slow Netshell / ENOS performance on ProxMox LXC

### ISSUE THREAD

**Issue by bmah888** [esnet/netshell#30]
Netshell / ENOS running on ProxMox LXC appears to be about 4 times slower than running on bare metal, similar hardware.

Timing from `bin/karaf` startup to the time that various output lines were emitted (in minutes:seconds).  First on LXC bmah-centos-177:

Output | Run 1 | Run 2 | Run 3
-----|-----|-----|-----|-----
GossipRouter started | 1:40 | 1:35 | 1:29
Hello Python | 3:21 | 3:35 | 3:34
Hello ODL MD-SAL | 4:46 | 5:10 | 5:15

Secondly on bare-metal aofa-tbn-1:

Output | Run 1 | Run 2 | Run 3
-----|-----|-----|-----|-----
GossipRouter started | 0:21 | 0:27 | 1:04
Hello Python | 0:56 | 1:02 | 1:19
Hello ODL MD-SAL | 1:10 | 1:19 | 1:26

mpstat(8) output generall showed higher CPU utilization on the bare-metal host, typically around 50% across all CPUs compared to typically around 12% across all cores for the Proxmox LXC case.

**Comment by lomaxfrog** [comment]
Based on measurement, and proxmox stats, it seems that the linux container does not spread the CPU load accross all cores. The CPU limit of the container may be incorrect for linux containers that requires a lot of CPU. It appears that loading OpenDaylight runs all physical cores at 70%.

**Comment by bmah888** [comment]
Update:  Set the CPU Limit parameter in the Proxmox UI to 0 and re-ran.  Times are now substantially improved and similar to the bare-metal times.

Output | Run 1 | Run 2 | Run 3
-----|-----|-----|-----|-----
GossipRouter started | 0:20 | 0:19 | 0:20
Hello Python | 0:44 | 0:40 | 0:42
Hello ODL MD-SAL | 1:07 | 1:06 | 1:10

(Information omitted earlier:  the LXC in question is hosted on denv-tbn-1.)

**Comment by lomaxfrog** [comment]
Setting 0 as CPU limit fixes the problem. However, this means we cannot really have more than one ODL/karaf container on the same physical host without having performance degradation.
